### PR TITLE
[#30] dialyzer warnings fixed

### LINKED ISSUE #30: Fix tests
Dialyzer meta test is failing 
```
{failed,{{badmatch,["sumo_store_riak.erl:490: The call sumo_store_riak:update_map(Conn::pid(),Bucket::{binary(),binary()},'undefined',{'map',[{{binary(),'counter' | 'flag' | 'map' | 'register' | 'set'},_}],[{{binary(),'counter' | 'flag' | 'map' | 'register' | 'set'},_}],[{binary(),'counter' | 'flag' | 'map' | 'register' | 'set'}],'undefined' | binary()},Opts::['if_none_match' | 'if_not_modified' | 'return_body' | 'return_head' | {'dw','all' | 'default' | 'one' | 'quorum' | non_neg_integer()} | {'n_val',pos_integer()} | {'pw','all' | 'default' | 'one' | 'quorum' | non_neg_integer()} | {'sloppy_quorum',boolean()} | {'w','all' | 'default' | 'one' | 'quorum' | non_neg_integer()}]) will never return since it differs in the 3rd argument from the success typing arguments: (pid(),{binary(),binary()},binary(),{'map',[{{_,_},_}],[{{_,_},_}],[{binary(),'counter' | 'flag' | 'map' | 'register' | 'set'}],'undefined' | binary()},[atom() | tuple()])\n"]},
         [{ktn_meta_SUITE,dialyzer,1,
                          [{file,"/Users/ferigis/workspace/erlang/inaka/sumo_db_riak/_build/test/lib/katana_test/src/ktn_meta_SUITE.erl"},
                           {line,73}]},
          {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1529}]},
          {test_server,run_test_case_eval1,6,
                       [{file,"test_server.erl"},{line,1045}]},
          {test_server,run_test_case_eval,9,
                       [{file,"test_server.erl"},{line,977}]}]}}
```

### PR DESCRIPTION
**Pull request by ferigis**
[close #30]

### CODE REVIEW

File: src/sumo_store_riak.erl [hunk 1]
```diff
@@ -38,6 +38,10 @@
 
 -include_lib("riakc/include/riakc.hrl").
 
+%% @todo it is needed with basho/riak-erlang-client 2.5.3. They already fixed on master so we should
```
Comment (elbrujohalcon) [inline src/sumo_store_riak.erl]: TODOs should start with a verb, like:
```erlang
%% @todo remove this when riakc … etc. etc.
```

The explanation can go below that line.
